"""Initial

Revision ID: 43e9887b3dfd
Revises: dafbd4eea1eb
Create Date: 2022-11-20 11:34:56.239815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43e9887b3dfd'
down_revision = 'dafbd4eea1eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_face',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__contact_face'))
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_face', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('legal', 'individual', name='type_of_client'), nullable=False),
    sa.ForeignKeyConstraint(['contact_face'], ['contact_face.id'], name=op.f('fk__clients__contact_face__contact_face'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__clients'))
    )
    op.create_table('tours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=False),
    sa.Column('days_count', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('without', 'three_times', 'with_breakfast', name='type_of_food'), nullable=False),
    sa.Column('tour_cost', sa.Float(precision=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk__tours__hotel_id__hotels'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__tours'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tours')
    op.drop_table('clients')
    op.drop_table('contact_face')
    # ### end Alembic commands ###
