"""Initial

Revision ID: 6759610b9c88
Revises: d23a7ae4f52a
Create Date: 2022-11-28 11:39:06.715351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6759610b9c88'
down_revision = 'd23a7ae4f52a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('pay_type', sa.Enum('credit', 'prepay', name='type_of_pay'), nullable=False),
    sa.Column('summary_cost', sa.Float(precision=2), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk__orders__client_id__clients'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__orders'))
    )
    op.create_table('tour_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('person_count', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(precision=2), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk__tour_info__order_id__orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], name=op.f('fk__tour_info__tour_id__tours'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__tour_info'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tour_info')
    op.drop_table('orders')
    # ### end Alembic commands ###
