"""Initial

Revision ID: 9914df60a12b
Revises: 1e7d81f16735
Create Date: 2022-11-14 21:48:53.779717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9914df60a12b'
down_revision = '1e7d81f16735'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
