"""Initial

Revision ID: cb2e16dd4ca6
Revises: 
Create Date: 2022-11-14 21:33:50.653135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb2e16dd4ca6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__admins'))
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__regions'))
    )
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name=op.f('fk__hotels__admin_id__admins'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['place_id'], ['regions.id'], name=op.f('fk__hotels__place_id__regions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__hotels'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hotels')
    op.drop_table('regions')
    op.drop_table('admins')
    # ### end Alembic commands ###
