"""Initial

Revision ID: d23a7ae4f52a
Revises: f40959b6bbc6
Create Date: 2022-11-25 00:05:48.220987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd23a7ae4f52a'
down_revision = 'f40959b6bbc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('days', sa.String(), nullable=False))
    op.drop_column('tours', 'days_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('days_count', sa.INTEGER(), nullable=False))
    op.drop_column('tours', 'days')
    # ### end Alembic commands ###
