"""Initial

Revision ID: dafbd4eea1eb
Revises: 9914df60a12b
Create Date: 2022-11-18 21:01:07.681353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dafbd4eea1eb'
down_revision = '9914df60a12b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
