"""Initial

Revision ID: f40959b6bbc6
Revises: 
Create Date: 2022-11-24 23:14:17.526616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f40959b6bbc6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__entities'))
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__regions'))
    )
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk__admins__entity_id__entities'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__admins'))
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('legal', 'individual', name='type_of_client'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk__clients__entity_id__entities'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__clients'))
    )
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name=op.f('fk__hotels__admin_id__admins'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['place_id'], ['regions.id'], name=op.f('fk__hotels__place_id__regions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__hotels'))
    )
    op.create_table('tours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=False),
    sa.Column('days_count', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('without', 'three_times', 'with_breakfast', name='type_of_food'), nullable=False),
    sa.Column('tour_cost', sa.Float(precision=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk__tours__hotel_id__hotels'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__tours'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tours')
    op.drop_table('hotels')
    op.drop_table('clients')
    op.drop_table('admins')
    op.drop_table('regions')
    op.drop_table('entities')
    # ### end Alembic commands ###
